// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: descriptor_set.proto

package descriptorsetpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DescriptorSet struct {
	state             protoimpl.MessageState          `protogen:"open.v1"`
	FileDescriptorSet *descriptorpb.FileDescriptorSet `protobuf:"bytes,1,opt,name=file_descriptor_set,json=fileDescriptorSet,proto3" json:"file_descriptor_set,omitempty"`
	MessageTypeIndex  map[string]*MessageTypeIndex    `protobuf:"bytes,2,rep,name=message_type_index,json=messageTypeIndex,proto3" json:"message_type_index,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	EnumTypeIndex     map[string]*EnumTypeIndex       `protobuf:"bytes,3,rep,name=enum_type_index,json=enumTypeIndex,proto3" json:"enum_type_index,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DescriptorSet) Reset() {
	*x = DescriptorSet{}
	mi := &file_descriptor_set_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescriptorSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescriptorSet) ProtoMessage() {}

func (x *DescriptorSet) ProtoReflect() protoreflect.Message {
	mi := &file_descriptor_set_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescriptorSet.ProtoReflect.Descriptor instead.
func (*DescriptorSet) Descriptor() ([]byte, []int) {
	return file_descriptor_set_proto_rawDescGZIP(), []int{0}
}

func (x *DescriptorSet) GetFileDescriptorSet() *descriptorpb.FileDescriptorSet {
	if x != nil {
		return x.FileDescriptorSet
	}
	return nil
}

func (x *DescriptorSet) GetMessageTypeIndex() map[string]*MessageTypeIndex {
	if x != nil {
		return x.MessageTypeIndex
	}
	return nil
}

func (x *DescriptorSet) GetEnumTypeIndex() map[string]*EnumTypeIndex {
	if x != nil {
		return x.EnumTypeIndex
	}
	return nil
}

type MessageTypeIndex struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JSON path to file from FileDescriptorSet ($). Always starts with $."1".
	FileJsonPath string `protobuf:"bytes,1,opt,name=file_json_path,json=fileJsonPath,proto3" json:"file_json_path,omitempty"` // e.g. $."1"."1"[0]
	// JSON path to type from FileDescriptorSet ($). Always starts with $."1". and is a subpath of file_json_path.
	TypeJsonPath string `protobuf:"bytes,2,opt,name=type_json_path,json=typeJsonPath,proto3" json:"type_json_path,omitempty"` // e.g. $."1"."1"[0]."4"[0]
	// message type
	FieldNameIndex   map[string]int32 `protobuf:"bytes,3,rep,name=field_name_index,json=fieldNameIndex,proto3" json:"field_name_index,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	FieldNumberIndex map[int32]int32  `protobuf:"bytes,4,rep,name=field_number_index,json=fieldNumberIndex,proto3" json:"field_number_index,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MessageTypeIndex) Reset() {
	*x = MessageTypeIndex{}
	mi := &file_descriptor_set_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageTypeIndex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageTypeIndex) ProtoMessage() {}

func (x *MessageTypeIndex) ProtoReflect() protoreflect.Message {
	mi := &file_descriptor_set_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageTypeIndex.ProtoReflect.Descriptor instead.
func (*MessageTypeIndex) Descriptor() ([]byte, []int) {
	return file_descriptor_set_proto_rawDescGZIP(), []int{1}
}

func (x *MessageTypeIndex) GetFileJsonPath() string {
	if x != nil {
		return x.FileJsonPath
	}
	return ""
}

func (x *MessageTypeIndex) GetTypeJsonPath() string {
	if x != nil {
		return x.TypeJsonPath
	}
	return ""
}

func (x *MessageTypeIndex) GetFieldNameIndex() map[string]int32 {
	if x != nil {
		return x.FieldNameIndex
	}
	return nil
}

func (x *MessageTypeIndex) GetFieldNumberIndex() map[int32]int32 {
	if x != nil {
		return x.FieldNumberIndex
	}
	return nil
}

type EnumTypeIndex struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JSON path to file from FileDescriptorSet ($). Always starts with $."1".
	FileJsonPath string `protobuf:"bytes,1,opt,name=file_json_path,json=fileJsonPath,proto3" json:"file_json_path,omitempty"` // e.g. $."1"."1"[0]
	// JSON path to type from FileDescriptorSet ($). Always starts with $."1". and is a subpath of file_json_path.
	TypeJsonPath string `protobuf:"bytes,2,opt,name=type_json_path,json=typeJsonPath,proto3" json:"type_json_path,omitempty"` // e.g. $."1"."1"[0]."4"[0]
	// enum type
	EnumNameIndex   map[string]int32 `protobuf:"bytes,3,rep,name=enum_name_index,json=enumNameIndex,proto3" json:"enum_name_index,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	EnumNumberIndex map[int32]int32  `protobuf:"bytes,4,rep,name=enum_number_index,json=enumNumberIndex,proto3" json:"enum_number_index,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EnumTypeIndex) Reset() {
	*x = EnumTypeIndex{}
	mi := &file_descriptor_set_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumTypeIndex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumTypeIndex) ProtoMessage() {}

func (x *EnumTypeIndex) ProtoReflect() protoreflect.Message {
	mi := &file_descriptor_set_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumTypeIndex.ProtoReflect.Descriptor instead.
func (*EnumTypeIndex) Descriptor() ([]byte, []int) {
	return file_descriptor_set_proto_rawDescGZIP(), []int{2}
}

func (x *EnumTypeIndex) GetFileJsonPath() string {
	if x != nil {
		return x.FileJsonPath
	}
	return ""
}

func (x *EnumTypeIndex) GetTypeJsonPath() string {
	if x != nil {
		return x.TypeJsonPath
	}
	return ""
}

func (x *EnumTypeIndex) GetEnumNameIndex() map[string]int32 {
	if x != nil {
		return x.EnumNameIndex
	}
	return nil
}

func (x *EnumTypeIndex) GetEnumNumberIndex() map[int32]int32 {
	if x != nil {
		return x.EnumNumberIndex
	}
	return nil
}

var File_descriptor_set_proto protoreflect.FileDescriptor

const file_descriptor_set_proto_rawDesc = "" +
	"\n" +
	"\x14descriptor_set.proto\x12\rmysqlprotobuf\x1a google/protobuf/descriptor.proto\"\xe4\x03\n" +
	"\rDescriptorSet\x12R\n" +
	"\x13file_descriptor_set\x18\x01 \x01(\v2\".google.protobuf.FileDescriptorSetR\x11fileDescriptorSet\x12`\n" +
	"\x12message_type_index\x18\x02 \x03(\v22.mysqlprotobuf.DescriptorSet.MessageTypeIndexEntryR\x10messageTypeIndex\x12W\n" +
	"\x0fenum_type_index\x18\x03 \x03(\v2/.mysqlprotobuf.DescriptorSet.EnumTypeIndexEntryR\renumTypeIndex\x1ad\n" +
	"\x15MessageTypeIndexEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x125\n" +
	"\x05value\x18\x02 \x01(\v2\x1f.mysqlprotobuf.MessageTypeIndexR\x05value:\x028\x01\x1a^\n" +
	"\x12EnumTypeIndexEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.mysqlprotobuf.EnumTypeIndexR\x05value:\x028\x01\"\xaa\x03\n" +
	"\x10MessageTypeIndex\x12$\n" +
	"\x0efile_json_path\x18\x01 \x01(\tR\ffileJsonPath\x12$\n" +
	"\x0etype_json_path\x18\x02 \x01(\tR\ftypeJsonPath\x12]\n" +
	"\x10field_name_index\x18\x03 \x03(\v23.mysqlprotobuf.MessageTypeIndex.FieldNameIndexEntryR\x0efieldNameIndex\x12c\n" +
	"\x12field_number_index\x18\x04 \x03(\v25.mysqlprotobuf.MessageTypeIndex.FieldNumberIndexEntryR\x10fieldNumberIndex\x1aA\n" +
	"\x13FieldNameIndexEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1aC\n" +
	"\x15FieldNumberIndexEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\x99\x03\n" +
	"\rEnumTypeIndex\x12$\n" +
	"\x0efile_json_path\x18\x01 \x01(\tR\ffileJsonPath\x12$\n" +
	"\x0etype_json_path\x18\x02 \x01(\tR\ftypeJsonPath\x12W\n" +
	"\x0fenum_name_index\x18\x03 \x03(\v2/.mysqlprotobuf.EnumTypeIndex.EnumNameIndexEntryR\renumNameIndex\x12]\n" +
	"\x11enum_number_index\x18\x04 \x03(\v21.mysqlprotobuf.EnumTypeIndex.EnumNumberIndexEntryR\x0fenumNumberIndex\x1a@\n" +
	"\x12EnumNameIndexEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1aB\n" +
	"\x14EnumNumberIndexEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01b\x06proto3"

var (
	file_descriptor_set_proto_rawDescOnce sync.Once
	file_descriptor_set_proto_rawDescData []byte
)

func file_descriptor_set_proto_rawDescGZIP() []byte {
	file_descriptor_set_proto_rawDescOnce.Do(func() {
		file_descriptor_set_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_descriptor_set_proto_rawDesc), len(file_descriptor_set_proto_rawDesc)))
	})
	return file_descriptor_set_proto_rawDescData
}

var file_descriptor_set_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_descriptor_set_proto_goTypes = []any{
	(*DescriptorSet)(nil),                  // 0: mysqlprotobuf.DescriptorSet
	(*MessageTypeIndex)(nil),               // 1: mysqlprotobuf.MessageTypeIndex
	(*EnumTypeIndex)(nil),                  // 2: mysqlprotobuf.EnumTypeIndex
	nil,                                    // 3: mysqlprotobuf.DescriptorSet.MessageTypeIndexEntry
	nil,                                    // 4: mysqlprotobuf.DescriptorSet.EnumTypeIndexEntry
	nil,                                    // 5: mysqlprotobuf.MessageTypeIndex.FieldNameIndexEntry
	nil,                                    // 6: mysqlprotobuf.MessageTypeIndex.FieldNumberIndexEntry
	nil,                                    // 7: mysqlprotobuf.EnumTypeIndex.EnumNameIndexEntry
	nil,                                    // 8: mysqlprotobuf.EnumTypeIndex.EnumNumberIndexEntry
	(*descriptorpb.FileDescriptorSet)(nil), // 9: google.protobuf.FileDescriptorSet
}
var file_descriptor_set_proto_depIdxs = []int32{
	9, // 0: mysqlprotobuf.DescriptorSet.file_descriptor_set:type_name -> google.protobuf.FileDescriptorSet
	3, // 1: mysqlprotobuf.DescriptorSet.message_type_index:type_name -> mysqlprotobuf.DescriptorSet.MessageTypeIndexEntry
	4, // 2: mysqlprotobuf.DescriptorSet.enum_type_index:type_name -> mysqlprotobuf.DescriptorSet.EnumTypeIndexEntry
	5, // 3: mysqlprotobuf.MessageTypeIndex.field_name_index:type_name -> mysqlprotobuf.MessageTypeIndex.FieldNameIndexEntry
	6, // 4: mysqlprotobuf.MessageTypeIndex.field_number_index:type_name -> mysqlprotobuf.MessageTypeIndex.FieldNumberIndexEntry
	7, // 5: mysqlprotobuf.EnumTypeIndex.enum_name_index:type_name -> mysqlprotobuf.EnumTypeIndex.EnumNameIndexEntry
	8, // 6: mysqlprotobuf.EnumTypeIndex.enum_number_index:type_name -> mysqlprotobuf.EnumTypeIndex.EnumNumberIndexEntry
	1, // 7: mysqlprotobuf.DescriptorSet.MessageTypeIndexEntry.value:type_name -> mysqlprotobuf.MessageTypeIndex
	2, // 8: mysqlprotobuf.DescriptorSet.EnumTypeIndexEntry.value:type_name -> mysqlprotobuf.EnumTypeIndex
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_descriptor_set_proto_init() }
func file_descriptor_set_proto_init() {
	if File_descriptor_set_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_descriptor_set_proto_rawDesc), len(file_descriptor_set_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_descriptor_set_proto_goTypes,
		DependencyIndexes: file_descriptor_set_proto_depIdxs,
		MessageInfos:      file_descriptor_set_proto_msgTypes,
	}.Build()
	File_descriptor_set_proto = out.File
	file_descriptor_set_proto_goTypes = nil
	file_descriptor_set_proto_depIdxs = nil
}
