// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: marshal_options.proto

package marshaloptionspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MarshalOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarshalOptions) Reset() {
	*x = MarshalOptions{}
	mi := &file_marshal_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarshalOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarshalOptions) ProtoMessage() {}

func (x *MarshalOptions) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarshalOptions.ProtoReflect.Descriptor instead.
func (*MarshalOptions) Descriptor() ([]byte, []int) {
	return file_marshal_options_proto_rawDescGZIP(), []int{0}
}

type UnmarshalOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnmarshalOptions) Reset() {
	*x = UnmarshalOptions{}
	mi := &file_marshal_options_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnmarshalOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmarshalOptions) ProtoMessage() {}

func (x *UnmarshalOptions) ProtoReflect() protoreflect.Message {
	mi := &file_marshal_options_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmarshalOptions.ProtoReflect.Descriptor instead.
func (*UnmarshalOptions) Descriptor() ([]byte, []int) {
	return file_marshal_options_proto_rawDescGZIP(), []int{1}
}

var File_marshal_options_proto protoreflect.FileDescriptor

const file_marshal_options_proto_rawDesc = "" +
	"\n" +
	"\x15marshal_options.proto\x12\rmysqlprotobuf\"\x10\n" +
	"\x0eMarshalOptions\"\x12\n" +
	"\x10UnmarshalOptionsb\x06proto3"

var (
	file_marshal_options_proto_rawDescOnce sync.Once
	file_marshal_options_proto_rawDescData []byte
)

func file_marshal_options_proto_rawDescGZIP() []byte {
	file_marshal_options_proto_rawDescOnce.Do(func() {
		file_marshal_options_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_marshal_options_proto_rawDesc), len(file_marshal_options_proto_rawDesc)))
	})
	return file_marshal_options_proto_rawDescData
}

var file_marshal_options_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_marshal_options_proto_goTypes = []any{
	(*MarshalOptions)(nil),   // 0: mysqlprotobuf.MarshalOptions
	(*UnmarshalOptions)(nil), // 1: mysqlprotobuf.UnmarshalOptions
}
var file_marshal_options_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_marshal_options_proto_init() }
func file_marshal_options_proto_init() {
	if File_marshal_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_marshal_options_proto_rawDesc), len(file_marshal_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_marshal_options_proto_goTypes,
		DependencyIndexes: file_marshal_options_proto_depIdxs,
		MessageInfos:      file_marshal_options_proto_msgTypes,
	}.Build()
	File_marshal_options_proto = out.File
	file_marshal_options_proto_goTypes = nil
	file_marshal_options_proto_depIdxs = nil
}
